### ISSUE TITLE
picasa real time data

### ISSUE THREAD

**Issue by geraldstanje** [tgulacsi/picago#4]
Hi,

how can you get location based real time data from picasa? I havnt found anything on google...

Thanks,
Gerald

**Comment by tgulacsi** [comment]
What do you mean under "location based real time data"?
You can get the location from picasa, and the time, but not realtime.

2015-03-22 13:52 GMT+01:00 geraldstanje notifications@github.com:

**Comment by geraldstanje** [comment]
images which are location tagged... i want to get all images for a lat, log within a spec. radius in realtime.

will i need to build a crawler?

**Comment by tgulacsi** [comment]
As https://developers.google.com/picasa-web/docs/2.0/reference#Parameters says, the "bbox" query parameter can be used for such searches.

For this, you may experiment with modifying code in getPhotos, to include a "&bbox=47.4895995,19.0486,48.4895995,20.0486" - first just simply append it to the photoURL, then you can fiddle out how to include this information into the API (i.e. have a GetPhotosSpec, with a Config, allowing all params which is allowed at https://developers.google.com/picasa-web/docs/2.0/reference#Parameters ?).

**Comment by tgulacsi** [comment]
You can check out the "queryparams" branch, and test my draft: GetPhotosSpec allows a QueryParams argument for specifyning the bounding box.
